package pe.ued.unsch.entities;
// Generated 25/06/2019 05:07:03 PM by Hibernate Tools 5.3.0.Beta2

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private Integer idproducto;
	private String nombre;
	private String descripcion;
	private int idproveedor;

	public Producto() {
	}

	public Producto(String nombre, String descripcion, int idproveedor) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.idproveedor = idproveedor;
	}

	public Integer getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(Integer idproducto) {
		this.idproducto = idproducto;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public int getIdproveedor() {
		return this.idproveedor;
	}

	public void setIdproveedor(int idproveedor) {
		this.idproveedor = idproveedor;
	}

}
