package pe.edu.unsch.entities;


import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;



// Generated 25/06/2019 05:07:03 PM by Hibernate Tools 5.3.0.Beta2

/**
 * Producto generated by hbm2java
 */

@Entity
@Table(name = "producto")
@Access(AccessType.FIELD)
public class Producto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY) //Para q el id sea Autoincrementable
	private Long idproducto;
	
	// column es como debe ir en la BD
	@Basic(optional = false)
	@NotNull
	@Size(min = 1, max = 150)
	@Column(name = "nombre")
	private String nombre; // este es como debe venir desde Angular	
	
	@Column(name = "descripcion")
	private String descripcion;
	
	//@Column(name = "idproveedor")
	//@OneToMany(mappedBy = "idproveedor", cascade = CascadeType.ALL) //
	@JoinColumn(name = "idproveedor",referencedColumnName = "idproveedor") //esto es para que no solo venga el ID si no toda la informacion de su llave foranea
	@ManyToOne
	private Proveedor idproveedor;
	
	
	public Producto() {
		
	}

	public Producto(Long idproducto, @NotNull @Size(min = 1, max = 150) String nombre, String descripcion,
			Proveedor idproveedor) {
		super();
		this.idproducto = idproducto;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.idproveedor = idproveedor;
	}

	public Long getIdproducto() {
		return idproducto;
	}

	public void setIdproducto(Long idproducto) {
		this.idproducto = idproducto;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Proveedor getIdproveedor() {
		return idproveedor;
	}

	public void setIdproveedor(Proveedor idproveedor) {
		this.idproveedor = idproveedor;
	}

	@Override
    public String toString() {
        return "Producto{" +
                "idproducto=" + idproducto +
                ", nombre='" + nombre + '\'' +
                ", descripcion='" + descripcion + '\''   +   
                ",idproveedor=" + idproveedor +
                '}';
    }


}
