package pe.edu.unsch.entities;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

// Generated 25/06/2019 05:07:03 PM by Hibernate Tools 5.3.0.Beta2

/**
 * Producto generated by hbm2java
 */

@Entity
@Table(name = "producto")
public class Producto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	private Long idproducto;
	
	// column es como debe ir en la BD
	@Basic(optional = false)
	@NotNull
	@Size(min = 1, max = 150)
	@Column(name = "nombre")
	private String nombre; // este es como debe venir desde Angular	
	
	@Column(name = "descripcion")
	private String descripcion;
	
	@Column(name = "idproveedor")
	private Long idproveedor;

	
	
	
	public Producto() {
		
	}

	public Producto(Long idproducto, @NotNull @Size(min = 1, max = 150) String nombre, String descripcion,
			Long idproveedor) {
		super();
		this.idproducto = idproducto;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.idproveedor = idproveedor;
	}

	public Long getIdproducto() {
		return idproducto;
	}

	public void setIdproducto(Long idproducto) {
		this.idproducto = idproducto;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Long getIdproveedor() {
		return idproveedor;
	}

	public void setIdproveedor(Long idproveedor) {
		this.idproveedor = idproveedor;
	}

	

}
